//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightToAskClient.Resx {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RightToAskClient.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutPagePopupText.
        /// </summary>
        internal static string AboutPagePopupText {
            get {
                return ResourceManager.GetString("AboutPagePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign user update message.
        /// </summary>
        internal static string AccountUpdateSigningError {
            get {
                return ResourceManager.GetString("AccountUpdateSigningError", resourceCulture);
            }
        }
        
        internal static string AddBackgroundPlaceholderText {
            get {
                return ResourceManager.GetString("AddBackgroundPlaceholderText", resourceCulture);
            }
        }
        
        internal static string AdvancedSearchButtonText {
            get {
                return ResourceManager.GetString("AdvancedSearchButtonText", resourceCulture);
            }
        }
        
        internal static string AnotherMPButtonText {
            get {
                return ResourceManager.GetString("AnotherMPButtonText", resourceCulture);
            }
        }
        
        internal static string AnotherUserButtonText {
            get {
                return ResourceManager.GetString("AnotherUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow other users to add more people to answer the question?.
        /// </summary>
        internal static string AnswererPermissions {
            get {
                return ResourceManager.GetString("AnswererPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnswerQuestionOptionsPopupText.
        /// </summary>
        internal static string AnswerQuestionOptionsPopupText {
            get {
                return ResourceManager.GetString("AnswerQuestionOptionsPopupText", resourceCulture);
            }
        }
        
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve this answer?.
        /// </summary>
        internal static string ApproveAnswerText {
            get {
                return ResourceManager.GetString("ApproveAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow other users to add more people to raise the question?.
        /// </summary>
        internal static string AskerPermissions {
            get {
                return ResourceManager.GetString("AskerPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities who should answer the question.
        /// </summary>
        internal static string AuthorityFilterLabelText {
            get {
                return ResourceManager.GetString("AuthorityFilterLabelText", resourceCulture);
            }
        }
        
        internal static string BackgroundHeaderText {
            get {
                return ResourceManager.GetString("BackgroundHeaderText", resourceCulture);
            }
        }
        
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        internal static string CitySuburbHeaderText {
            get {
                return ResourceManager.GetString("CitySuburbHeaderText", resourceCulture);
            }
        }
        
        internal static string ClickForFiltersText {
            get {
                return ResourceManager.GetString("ClickForFiltersText", resourceCulture);
            }
        }
        
        internal static string CompleteAccountCreationButtonText {
            get {
                return ResourceManager.GetString("CompleteAccountCreationButtonText", resourceCulture);
            }
        }
        
        internal static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewAccountPopupText.
        /// </summary>
        internal static string CreateNewAccountPopupText {
            get {
                return ResourceManager.GetString("CreateNewAccountPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct my question.
        /// </summary>
        internal static string DirectMyQuestionTitle {
            get {
                return ResourceManager.GetString("DirectMyQuestionTitle", resourceCulture);
            }
        }
        
        internal static string DiscardDraftButtonText {
            get {
                return ResourceManager.GetString("DiscardDraftButtonText", resourceCulture);
            }
        }
        
        internal static string DisplayNameHeaderText {
            get {
                return ResourceManager.GetString("DisplayNameHeaderText", resourceCulture);
            }
        }
        
        internal static string DisplayNamePlaceholderText {
            get {
                return ResourceManager.GetString("DisplayNamePlaceholderText", resourceCulture);
            }
        }
        
        internal static string DMButtonText {
            get {
                return ResourceManager.GetString("DMButtonText", resourceCulture);
            }
        }
        
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        internal static string DraftQuestionPlaceholderText {
            get {
                return ResourceManager.GetString("DraftQuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAccountPopupText.
        /// </summary>
        internal static string EditAccountPopupText {
            get {
                return ResourceManager.GetString("EditAccountPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Profile.
        /// </summary>
        internal static string EditProfileButtonText {
            get {
                return ResourceManager.GetString("EditProfileButtonText", resourceCulture);
            }
        }
        
        internal static string EditYourAccountTitle {
            get {
                return ResourceManager.GetString("EditYourAccountTitle", resourceCulture);
            }
        }
        
        internal static string ElectoratesHeaderText {
            get {
                return ResourceManager.GetString("ElectoratesHeaderText", resourceCulture);
            }
        }
        
        internal static string ElectoratesKnownHeaderText {
            get {
                return ResourceManager.GetString("ElectoratesKnownHeaderText", resourceCulture);
            }
        }
        
        internal static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        internal static string ExpiringSoonButtonText {
            get {
                return ResourceManager.GetString("ExpiringSoonButtonText", resourceCulture);
            }
        }
        
        internal static string FailedToUpdateAccountText {
            get {
                return ResourceManager.GetString("FailedToUpdateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiltersPopupText.
        /// </summary>
        internal static string FiltersPopupText {
            get {
                return ResourceManager.GetString("FiltersPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Committee.
        /// </summary>
        internal static string FindCommitteeButtonText {
            get {
                return ResourceManager.GetString("FindCommitteeButtonText", resourceCulture);
            }
        }
        
        internal static string FindElectoratesButtonText {
            get {
                return ResourceManager.GetString("FindElectoratesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindMPsPopupText.
        /// </summary>
        internal static string FindMPsPopupText {
            get {
                return ResourceManager.GetString("FindMPsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find My Electorates.
        /// </summary>
        internal static string FindMyElectoratesButtonText {
            get {
                return ResourceManager.GetString("FindMyElectoratesButtonText", resourceCulture);
            }
        }
        
        internal static string FindQuestionsTitle {
            get {
                return ResourceManager.GetString("FindQuestionsTitle", resourceCulture);
            }
        }
        
        internal static string FocusSupportInstructionReadingOnly {
            get {
                return ResourceManager.GetString("FocusSupportInstructionReadingOnly", resourceCulture);
            }
        }
        
        internal static string FocusSupportInstructionQuestionDrafting {
            get {
                return ResourceManager.GetString("FocusSupportInstructionQuestionDrafting", resourceCulture);
            }
        }
        
        internal static string FocusSupportReport {
            get {
                return ResourceManager.GetString("FocusSupportReport", resourceCulture);
            }
        }
        
        internal static string FollowButtonText {
            get {
                return ResourceManager.GetString("FollowButtonText", resourceCulture);
            }
        }
        
        internal static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Popup Button.
        /// </summary>
        internal static string InfoPopupButtonText {
            get {
                return ResourceManager.GetString("InfoPopupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep for upload.
        /// </summary>
        internal static string KeepQuestionButtonText {
            get {
                return ResourceManager.GetString("KeepQuestionButtonText", resourceCulture);
            }
        }
        
        internal static string KeywordEntryPlaceholderText {
            get {
                return ResourceManager.GetString("KeywordEntryPlaceholderText", resourceCulture);
            }
        }
        
        internal static string LinkAnswerHeaderText {
            get {
                return ResourceManager.GetString("LinkAnswerHeaderText", resourceCulture);
            }
        }
        
        internal static string LinkAnswerPlaceholderText {
            get {
                return ResourceManager.GetString("LinkAnswerPlaceholderText", resourceCulture);
            }
        }
        
        internal static string LookupElectoratesHeaderText {
            get {
                return ResourceManager.GetString("LookupElectoratesHeaderText", resourceCulture);
            }
        }
        
        internal static string MainPageHeader2Text {
            get {
                return ResourceManager.GetString("MainPageHeader2Text", resourceCulture);
            }
        }
        
        internal static string MainPageHeaderText {
            get {
                return ResourceManager.GetString("MainPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your political questions have an impact.
        /// </summary>
        internal static string MainPageHeadingText {
            get {
                return ResourceManager.GetString("MainPageHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPagePopupText.
        /// </summary>
        internal static string MainPagePopupText {
            get {
                return ResourceManager.GetString("MainPagePopupText", resourceCulture);
            }
        }
        
        internal static string MPAnswerFilterLabelText {
            get {
                return ResourceManager.GetString("MPAnswerFilterLabelText", resourceCulture);
            }
        }
        
        internal static string MPDataStillInitializing {
            get {
                return ResourceManager.GetString("MPDataStillInitializing", resourceCulture);
            }
        }
        
        internal static string MPRaiseFilterLabelText {
            get {
                return ResourceManager.GetString("MPRaiseFilterLabelText", resourceCulture);
            }
        }
        
        internal static string MPsHeaderText1 {
            get {
                return ResourceManager.GetString("MPsHeaderText1", resourceCulture);
            }
        }
        
        internal static string MPsHeaderText2 {
            get {
                return ResourceManager.GetString("MPsHeaderText2", resourceCulture);
            }
        }
        
        internal static string MyMPButtonText {
            get {
                return ResourceManager.GetString("MyMPButtonText", resourceCulture);
            }
        }
        
        internal static string MyQuestionPlaceholderText {
            get {
                return ResourceManager.GetString("MyQuestionPlaceholderText", resourceCulture);
            }
        }
        
        internal static string MyQuestionTitleText {
            get {
                return ResourceManager.GetString("MyQuestionTitleText", resourceCulture);
            }
        }
        
        internal static string NavigateOKText {
            get {
                return ResourceManager.GetString("NavigateOKText", resourceCulture);
            }
        }
        
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        internal static string NotSureButtonText {
            get {
                return ResourceManager.GetString("NotSureButtonText", resourceCulture);
            }
        }
        
        internal static string NoUpperHousePickerTitle {
            get {
                return ResourceManager.GetString("NoUpperHousePickerTitle", resourceCulture);
            }
        }
        
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        internal static string OrHeaderText {
            get {
                return ResourceManager.GetString("OrHeaderText", resourceCulture);
            }
        }
        
        internal static string OtherMPAnswerFilterLabelText {
            get {
                return ResourceManager.GetString("OtherMPAnswerFilterLabelText", resourceCulture);
            }
        }
        
        internal static string OtherMPRaiseFilterLabelText {
            get {
                return ResourceManager.GetString("OtherMPRaiseFilterLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Profile.
        /// </summary>
        internal static string OtherUserProfileTitle {
            get {
                return ResourceManager.GetString("OtherUserProfileTitle", resourceCulture);
            }
        }
        
        internal static string PostcodeHeaderText {
            get {
                return ResourceManager.GetString("PostcodeHeaderText", resourceCulture);
            }
        }
        
        internal static string PublicAuthorityButtonText {
            get {
                return ResourceManager.GetString("PublicAuthorityButtonText", resourceCulture);
            }
        }
        
        internal static string PublishQuestionButtonText {
            get {
                return ResourceManager.GetString("PublishQuestionButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question Details.
        /// </summary>
        internal static string QuestionDetailsTitle
        {
            get {
                return ResourceManager.GetString("QuestionDetailsTitle", resourceCulture);
            }
        }
        
        internal static string QuestionHeaderText {
            get {
                return ResourceManager.GetString("QuestionHeaderText", resourceCulture);
            }
        }
        
        internal static string QuestionWriterHeaderText {
            get {
                return ResourceManager.GetString("QuestionWriterHeaderText", resourceCulture);
            }
        }
        
        internal static string ReadingPageHeader1 {
            get {
                return ResourceManager.GetString("ReadingPageHeader1", resourceCulture);
            }
        }
        
        internal static string ReadingPageQuestionDraftingHeader1 {
            get {
                return ResourceManager.GetString("ReadingPageQuestionDraftingHeader1", resourceCulture);
            }
        }
        
        internal static string ReadQuestionsTitle {
            get {
                return ResourceManager.GetString("ReadQuestionsTitle", resourceCulture);
            }
        }
        
        internal static string RecentQuestionsTitle {
            get {
                return ResourceManager.GetString("RecentQuestionsTitle", resourceCulture);
            }
        }
        
        internal static string RegisterMPAccountButtonText {
            get {
                return ResourceManager.GetString("RegisterMPAccountButtonText", resourceCulture);
            }
        }
        
        internal static string RegisterOrganisationAccountButtonText {
            get {
                return ResourceManager.GetString("RegisterOrganisationAccountButtonText", resourceCulture);
            }
        }
        
        internal static string SaveAnswerButtonText {
            get {
                return ResourceManager.GetString("SaveAnswerButtonText", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderText", resourceCulture);
            }
        }
        
        internal static string SeeQuestionsButtonText {
            get {
                return ResourceManager.GetString("SeeQuestionsButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectButtonText
        {
            get {
                return ResourceManager.GetString("SelectButtonText", resourceCulture);
            }
        }
        
        internal static string SelectedButtonText {
            get {
                return ResourceManager.GetString("SelectedButtonText", resourceCulture);
            }
        }
        
        internal static string SelectStateWarningText {
            get {
                return ResourceManager.GetString("SelectStateWarningText", resourceCulture);
            }
        }
        
        internal static string ServerConfigErrorRecommendation {
            get {
                return ResourceManager.GetString("ServerConfigErrorRecommendation", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to OtherUserProfilePopupText.
        /// </summary>
        internal static string OtherUserProfilePopupText {
            get {
                return ResourceManager.GetString("OtherUserProfilePopupText", resourceCulture);
            }
        }

        internal static string ServerConfigErrorText
        {
            get {
                return ResourceManager.GetString("ServerConfigErrorText", resourceCulture);
            }
        }
        
        internal static string SimilarQuestionsTitle {
            get {
                return ResourceManager.GetString("SimilarQuestionsTitle", resourceCulture);
            }
        }
        
        internal static string SkipStepButton {
            get {
                return ResourceManager.GetString("SkipStepButton", resourceCulture);
            }
        }
        
        internal static string StartDraftingButtonText {
            get {
                return ResourceManager.GetString("StartDraftingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionAskerPopupText.
        /// </summary>
        internal static string QuestionAskerPopupText {
            get {
                return ResourceManager.GetString("QuestionAskerPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionDetailPopupText.
        /// </summary>
        internal static string QuestionDetailPopupText {
            get {
                return ResourceManager.GetString("QuestionDetailPopupText", resourceCulture);
            }
        }
        
        internal static string StateHeaderText {
            get {
                return ResourceManager.GetString("StateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Popup Test for Drafting Question.
        /// </summary>
        internal static string QuestionDraftingPagePopupText {
            get {
                return ResourceManager.GetString("QuestionDraftingPagePopupText", resourceCulture);
            }
        }
        
        internal static string Step2BodyText1 {
            get {
                return ResourceManager.GetString("Step2BodyText1", resourceCulture);
            }
        }
        
        internal static string Step2BodyText2 {
            get {
                return ResourceManager.GetString("Step2BodyText2", resourceCulture);
            }
        }
        
        internal static string Step2BodyText3 {
            get {
                return ResourceManager.GetString("Step2BodyText3", resourceCulture);
            }
        }
        
        internal static string Step2BodyText4 {
            get {
                return ResourceManager.GetString("Step2BodyText4", resourceCulture);
            }
        }
        
        internal static string Step2BodyText5 {
            get {
                return ResourceManager.GetString("Step2BodyText5", resourceCulture);
            }
        }
        
        internal static string Step2BodyText6 {
            get {
                return ResourceManager.GetString("Step2BodyText6", resourceCulture);
            }
        }
        
        internal static string Step2BodyText7 {
            get {
                return ResourceManager.GetString("Step2BodyText7", resourceCulture);
            }
        }
        
        internal static string RaiseQuestionTitle {
            get {
                return ResourceManager.GetString("RaiseQuestionTitle", resourceCulture);
            }
        }
        
        internal static string StreetHeaderText {
            get {
                return ResourceManager.GetString("StreetHeaderText", resourceCulture);
            }
        }
        
        internal static string SuccessfullyUpdatedAccountText {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedAccountText", resourceCulture);
            }
        }
        
        internal static string TapToEditFiltersText {
            get {
                return ResourceManager.GetString("TapToEditFiltersText", resourceCulture);
            }
        }
        
        internal static string ToBeAnsweredByText {
            get {
                return ResourceManager.GetString("ToBeAnsweredByText", resourceCulture);
            }
        }
        
        internal static string TrendingButtonText {
            get {
                return ResourceManager.GetString("TrendingButtonText", resourceCulture);
            }
        }
        
        internal static string UIDHeaderText {
            get {
                return ResourceManager.GetString("UIDHeaderText", resourceCulture);
            }
        }
        
        internal static string UIDPlaceholderText {
            get {
                return ResourceManager.GetString("UIDPlaceholderText", resourceCulture);
            }
        }
        
        internal static string UpdateAccountButtonText {
            get {
                return ResourceManager.GetString("UpdateAccountButtonText", resourceCulture);
            }
        }
        
        internal static string UpvoteButtonText {
            get {
                return ResourceManager.GetString("UpvoteButtonText", resourceCulture);
            }
        }
        
        internal static string UpvotedButtonText {
            get {
                return ResourceManager.GetString("UpvotedButtonText", resourceCulture);
            }
        }
        
        internal static string UpvotesHeaderText {
            get {
                return ResourceManager.GetString("UpvotesHeaderText", resourceCulture);
            }
        }
        
        internal static string UserProfileTitle {
            get {
                return ResourceManager.GetString("UserProfileTitle", resourceCulture);
            }
        }
        
        internal static string ViewOtherUserProfile {
            get {
                return ResourceManager.GetString("ViewOtherUserProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This link is outside Right To Ask .
        /// </summary>
        internal static string WebNavigationWarning
        {
            get {
                return ResourceManager.GetString("WebNavigationWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to open it in a web browser?.
        /// </summary>
        internal static string WebNavigationRequest
        {
            get {
                return ResourceManager.GetString("WebNavigationRequest", resourceCulture);
            }
        }
        
        internal static string UpdateMPsButtonText {
            get {
                return ResourceManager.GetString("UpdateMPsButtonText", resourceCulture);
            }
        }
        
        internal static string EditQuestionButtonText {
            get {
                return ResourceManager.GetString("EditQuestionButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question was edited successfully..
        /// </summary>
        internal static string QuestionEditSuccessfulPopupText
        {
            get {
                return ResourceManager.GetString("QuestionEditSuccessfulPopupText", resourceCulture);
            }
        }
        
        internal static string DraftMyQuestionTitle {
            get {
                return ResourceManager.GetString("DraftMyQuestionTitle", resourceCulture);
            }
        }
        
        internal static string RaiseQuestionHeaderText {
            get {
                return ResourceManager.GetString("RaiseQuestionHeaderText", resourceCulture);
            }
        }
        
        internal static string OptionAText1 {
            get {
                return ResourceManager.GetString("OptionAText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectableListAuthoritiesPopupText.
        /// </summary>
        internal static string SelectableListAuthoritiesPopupText {
            get {
                return ResourceManager.GetString("SelectableListAuthoritiesPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectableListMPsPopupText.
        /// </summary>
        internal static string SelectableListMPsPopupText {
            get {
                return ResourceManager.GetString("SelectableListMPsPopupText", resourceCulture);
            }
        }
        
        internal static string OptionAText2 {
            get {
                return ResourceManager.GetString("OptionAText2", resourceCulture);
            }
        }
        
        internal static string OptionAText3 {
            get {
                return ResourceManager.GetString("OptionAText3", resourceCulture);
            }
        }
        
        internal static string OptionAText4 {
            get {
                return ResourceManager.GetString("OptionAText4", resourceCulture);
            }
        }
        
        internal static string OptionBText1 {
            get {
                return ResourceManager.GetString("OptionBText1", resourceCulture);
            }
        }
        
        internal static string OptionBText2 {
            get {
                return ResourceManager.GetString("OptionBText2", resourceCulture);
            }
        }
        
        internal static string OptionBText3 {
            get {
                return ResourceManager.GetString("OptionBText3", resourceCulture);
            }
        }
        
        internal static string OptionBText4 {
            get {
                return ResourceManager.GetString("OptionBText4", resourceCulture);
            }
        }
        
        internal static string WhoShouldAnswerTitle {
            get {
                return ResourceManager.GetString("WhoShouldAnswerTitle", resourceCulture);
            }
        }
        
        internal static string DraftImageAccessibilityHelpText {
            get {
                return ResourceManager.GetString("DraftImageAccessibilityHelpText", resourceCulture);
            }
        }
        
        internal static string DraftImageAccessibilityNameText {
            get {
                return ResourceManager.GetString("DraftImageAccessibilityNameText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read and upvote questions.
        /// </summary>
        internal static string MainPageSubheader1Text
        {
            get {
                return ResourceManager.GetString("MainPageSubheader1Text", resourceCulture);
            }
        }
        
        internal static string MainPageSubheader2Text {
            get {
                return ResourceManager.GetString("MainPageSubheader2Text", resourceCulture);
            }
        }
        
        internal static string MainPageSubheader3Text {
            get {
                return ResourceManager.GetString("MainPageSubheader3Text", resourceCulture);
            }
        }
        
        internal static string MainPageTrendingNowAccessibilityLabelHelpText {
            get {
                return ResourceManager.GetString("MainPageTrendingNowAccessibilityLabelHelpText", resourceCulture);
            }
        }
        
        internal static string MainPageTrendingNowAccessibilityLabelName {
            get {
                return ResourceManager.GetString("MainPageTrendingNowAccessibilityLabelName", resourceCulture);
            }
        }
        
        internal static string ReadAndUpvoteFrameSubtext {
            get {
                return ResourceManager.GetString("ReadAndUpvoteFrameSubtext", resourceCulture);
            }
        }
        
        internal static string ReadAndUpvoteImageAccessibilityHelpText {
            get {
                return ResourceManager.GetString("ReadAndUpvoteImageAccessibilityHelpText", resourceCulture);
            }
        }
        
        internal static string ReadAndUpvoteImageAccessibilityNameText {
            get {
                return ResourceManager.GetString("ReadAndUpvoteImageAccessibilityNameText", resourceCulture);
            }
        }
        
        internal static string SearchBarTitle {
            get {
                return ResourceManager.GetString("SearchBarTitle", resourceCulture);
            }
        }
        
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        internal static string YourQuestionTitleText {
            get {
                return ResourceManager.GetString("YourQuestionTitleText", resourceCulture);
            }
        }
        
        internal static string CreateAccountPopUpText {
            get {
                return ResourceManager.GetString("CreateAccountPopUpText", resourceCulture);
            }
        }
        
        internal static string MakeAccountQuestionText {
            get {
                return ResourceManager.GetString("MakeAccountQuestionText", resourceCulture);
            }
        }
        
        internal static string NotNowAnswerText {
            get {
                return ResourceManager.GetString("NotNowAnswerText", resourceCulture);
            }
        }
        
        internal static string EmptyQuestionCollectionViewString {
            get {
                return ResourceManager.GetString("EmptyQuestionCollectionViewString", resourceCulture);
            }
        }
        
        internal static string SearchFrameSubtext {
            get {
                return ResourceManager.GetString("SearchFrameSubtext", resourceCulture);
            }
        }
        
        internal static string QuestionFrameAnswerButtonAccessibilityName {
            get {
                return ResourceManager.GetString("QuestionFrameAnswerButtonAccessibilityName", resourceCulture);
            }
        }
        
        internal static string QuestionFrameAnswerButtonAccessibilityText {
            get {
                return ResourceManager.GetString("QuestionFrameAnswerButtonAccessibilityText", resourceCulture);
            }
        }
        
        internal static string QuestionFrameFlagButtonAccessibilityName {
            get {
                return ResourceManager.GetString("QuestionFrameFlagButtonAccessibilityName", resourceCulture);
            }
        }
        
        internal static string QuestionFrameFlagButtonAccessibilityText {
            get {
                return ResourceManager.GetString("QuestionFrameFlagButtonAccessibilityText", resourceCulture);
            }
        }
        
        internal static string QuestionFrameFlagButtonAccessibilityTextRed {
            get {
                return ResourceManager.GetString("QuestionFrameFlagButtonAccessibilityTextRed", resourceCulture);
            }
        }
        
        internal static string QuestionFrameShareButtonAccessibilityName {
            get {
                return ResourceManager.GetString("QuestionFrameShareButtonAccessibilityName", resourceCulture);
            }
        }
        
        internal static string QuestionFrameShareButtonAccessibilityText {
            get {
                return ResourceManager.GetString("QuestionFrameShareButtonAccessibilityText", resourceCulture);
            }
        }
        
        internal static string QuestionFrameThumbsUpAccessibilityName {
            get {
                return ResourceManager.GetString("QuestionFrameThumbsUpAccessibilityName", resourceCulture);
            }
        }
        
        internal static string QuestionFrameThumbsUpAccessibilityText {
            get {
                return ResourceManager.GetString("QuestionFrameThumbsUpAccessibilityText", resourceCulture);
            }
        }
    }
}
