//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightToAskClient.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RightToAskClient.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string AdvancedSearchButtonText {
            get {
                return ResourceManager.GetString("AdvancedSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another MP.
        /// </summary>
        internal static string AnotherMPButtonText {
            get {
                return ResourceManager.GetString("AnotherMPButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another RightToAsk User.
        /// </summary>
        internal static string AnotherUserButtonText {
            get {
                return ResourceManager.GetString("AnotherUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right To Ask.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct my question.
        /// </summary>
        internal static string DirectMyQuestionTitle {
            get {
                return ResourceManager.GetString("DirectMyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Draft.
        /// </summary>
        internal static string DiscardDraftButtonText {
            get {
                return ResourceManager.GetString("DiscardDraftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Soon.
        /// </summary>
        internal static string ExpiringSoonButtonText {
            get {
                return ResourceManager.GetString("ExpiringSoonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Committee.
        /// </summary>
        internal static string FindCommitteeButtonText {
            get {
                return ResourceManager.GetString("FindCommitteeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Questions.
        /// </summary>
        internal static string FindQuestionsTitle {
            get {
                return ResourceManager.GetString("FindQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a question.
        /// </summary>
        internal static string MainPageHeader2Text {
            get {
                return ResourceManager.GetString("MainPageHeader2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and vote on questions.
        /// </summary>
        internal static string MainPageHeaderText {
            get {
                return ResourceManager.GetString("MainPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Data is still being initialized..
        /// </summary>
        internal static string MPDataStillInitializing {
            get {
                return ResourceManager.GetString("MPDataStillInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My MP.
        /// </summary>
        internal static string MyMPButtonText {
            get {
                return ResourceManager.GetString("MyMPButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question (max 280  chars)
        ///
        ///
        ///
        ///                                                               ?.
        /// </summary>
        internal static string MyQuestionPlaceholderText {
            get {
                return ResourceManager.GetString("MyQuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My question is....
        /// </summary>
        internal static string MyQuestionTitleText {
            get {
                return ResourceManager.GetString("MyQuestionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sure.
        /// </summary>
        internal static string NotSureButtonText {
            get {
                return ResourceManager.GetString("NotSureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Public Authority.
        /// </summary>
        internal static string PublicAuthorityButtonText {
            get {
                return ResourceManager.GetString("PublicAuthorityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectButtonText {
            get {
                return ResourceManager.GetString("SelectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected!.
        /// </summary>
        internal static string SelectedButtonText {
            get {
                return ResourceManager.GetString("SelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Drafting.
        /// </summary>
        internal static string StartDraftingButtonText {
            get {
                return ResourceManager.GetString("StartDraftingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll help you direct your question to where it might get answered.
        /// </summary>
        internal static string Step2BodyText1 {
            get {
                return ResourceManager.GetString("Step2BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should it be raised by....
        /// </summary>
        internal static string Step2BodyText2 {
            get {
                return ResourceManager.GetString("Step2BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Parliamentary Committee, such as Senate Estimates?.
        /// </summary>
        internal static string Step2BodyText3 {
            get {
                return ResourceManager.GetString("Step2BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or by your MP, perhaps in a special session for constituent questions?.
        /// </summary>
        internal static string Step2BodyText4 {
            get {
                return ResourceManager.GetString("Step2BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or by some other MP?.
        /// </summary>
        internal static string Step2BodyText5 {
            get {
                return ResourceManager.GetString("Step2BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a journalist or other RightToAsk participant?.
        /// </summary>
        internal static string Step2BodyText6 {
            get {
                return ResourceManager.GetString("Step2BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or are you just not sure?.
        /// </summary>
        internal static string Step2BodyText7 {
            get {
                return ResourceManager.GetString("Step2BodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        internal static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be answered by.
        /// </summary>
        internal static string ToBeAnsweredByText {
            get {
                return ResourceManager.GetString("ToBeAnsweredByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Now.
        /// </summary>
        internal static string TrendingNowButtonText {
            get {
                return ResourceManager.GetString("TrendingNowButtonText", resourceCulture);
            }
        }
    }
}
