//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightToAskClient.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RightToAskClient.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign user update message.
        /// </summary>
        internal static string AccountUpdateSigningError {
            get {
                return ResourceManager.GetString("AccountUpdateSigningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Background (optional).
        /// </summary>
        internal static string AddBackgroundPlaceholderText {
            get {
                return ResourceManager.GetString("AddBackgroundPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string AdvancedSearchButtonText {
            get {
                return ResourceManager.GetString("AdvancedSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another MP.
        /// </summary>
        internal static string AnotherMPButtonText {
            get {
                return ResourceManager.GetString("AnotherMPButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another RightToAsk User.
        /// </summary>
        internal static string AnotherUserButtonText {
            get {
                return ResourceManager.GetString("AnotherUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right To Ask.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities who should answer the question.
        /// </summary>
        internal static string AuthorityFilterLabelText {
            get {
                return ResourceManager.GetString("AuthorityFilterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        internal static string BackgroundHeaderText {
            get {
                return ResourceManager.GetString("BackgroundHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or suburb.
        /// </summary>
        internal static string CitySuburbHeaderText {
            get {
                return ResourceManager.GetString("CitySuburbHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Filters.
        /// </summary>
        internal static string ClickForFiltersText {
            get {
                return ResourceManager.GetString("ClickForFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Account Creation.
        /// </summary>
        internal static string CompleteAccountCreationButtonText {
            get {
                return ResourceManager.GetString("CompleteAccountCreationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct my question.
        /// </summary>
        internal static string DirectMyQuestionTitle {
            get {
                return ResourceManager.GetString("DirectMyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Draft.
        /// </summary>
        internal static string DiscardDraftButtonText {
            get {
                return ResourceManager.GetString("DiscardDraftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayNameHeaderText {
            get {
                return ResourceManager.GetString("DisplayNameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter display name.
        /// </summary>
        internal static string DisplayNamePlaceholderText {
            get {
                return ResourceManager.GetString("DisplayNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Direct Message to {0}.
        /// </summary>
        internal static string DMButtonText {
            get {
                return ResourceManager.GetString("DMButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft a Question.
        /// </summary>
        internal static string DraftMyQuestionTitle {
            get {
                return ResourceManager.GetString("DraftMyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Question: .
        /// </summary>
        internal static string DraftQuestionPlaceholderText {
            get {
                return ResourceManager.GetString("DraftQuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Profile.
        /// </summary>
        internal static string EditProfileButtonText {
            get {
                return ResourceManager.GetString("EditProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        internal static string EditQuestionButtonText {
            get {
                return ResourceManager.GetString("EditQuestionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Account.
        /// </summary>
        internal static string EditYourAccountTitle {
            get {
                return ResourceManager.GetString("EditYourAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electorates:.
        /// </summary>
        internal static string ElectoratesHeaderText {
            get {
                return ResourceManager.GetString("ElectoratesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know my electorates already.
        /// </summary>
        internal static string ElectoratesKnownHeaderText {
            get {
                return ResourceManager.GetString("ElectoratesKnownHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Soon.
        /// </summary>
        internal static string ExpiringSoonButtonText {
            get {
                return ResourceManager.GetString("ExpiringSoonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error: Your account details could not be changed at this time..
        /// </summary>
        internal static string FailedToUpdateAccountText {
            get {
                return ResourceManager.GetString("FailedToUpdateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Committee.
        /// </summary>
        internal static string FindCommitteeButtonText {
            get {
                return ResourceManager.GetString("FindCommitteeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next: Find Your Electorates.
        /// </summary>
        internal static string FindElectoratesButtonText {
            get {
                return ResourceManager.GetString("FindElectoratesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find My Electorates.
        /// </summary>
        internal static string FindMyElectoratesButtonText {
            get {
                return ResourceManager.GetString("FindMyElectoratesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Questions.
        /// </summary>
        internal static string FindQuestionsTitle {
            get {
                return ResourceManager.GetString("FindQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow {0}.
        /// </summary>
        internal static string FollowButtonText {
            get {
                return ResourceManager.GetString("FollowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Question: Review for Upload.
        /// </summary>
        internal static string KeepQuestionButtonText {
            get {
                return ResourceManager.GetString("KeepQuestionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string KeywordEntryPlaceholderText {
            get {
                return ResourceManager.GetString("KeywordEntryPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link or Answer:.
        /// </summary>
        internal static string LinkAnswerHeaderText {
            get {
                return ResourceManager.GetString("LinkAnswerHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an answer or a Hansard link to an answer.
        /// </summary>
        internal static string LinkAnswerPlaceholderText {
            get {
                return ResourceManager.GetString("LinkAnswerPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to look them up.
        /// </summary>
        internal static string LookupElectoratesHeaderText {
            get {
                return ResourceManager.GetString("LookupElectoratesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a question.
        /// </summary>
        internal static string MainPageHeader2Text {
            get {
                return ResourceManager.GetString("MainPageHeader2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and vote on questions.
        /// </summary>
        internal static string MainPageHeaderText {
            get {
                return ResourceManager.GetString("MainPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My MPs who should answer the question.
        /// </summary>
        internal static string MPAnswerFilterLabelText {
            get {
                return ResourceManager.GetString("MPAnswerFilterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Data is still being initialized..
        /// </summary>
        internal static string MPDataStillInitializing {
            get {
                return ResourceManager.GetString("MPDataStillInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My MPs who should raise the question in Parliament.
        /// </summary>
        internal static string MPRaiseFilterLabelText {
            get {
                return ResourceManager.GetString("MPRaiseFilterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MPs are defined by where you live.
        /// </summary>
        internal static string MPsHeaderText1 {
            get {
                return ResourceManager.GetString("MPsHeaderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I live in .
        /// </summary>
        internal static string MPsHeaderText2 {
            get {
                return ResourceManager.GetString("MPsHeaderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My MP.
        /// </summary>
        internal static string MyMPButtonText {
            get {
                return ResourceManager.GetString("MyMPButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question (max 280  chars)
        ///
        ///
        ///
        ///                                                               ?.
        /// </summary>
        internal static string MyQuestionPlaceholderText {
            get {
                return ResourceManager.GetString("MyQuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My question is....
        /// </summary>
        internal static string MyQuestionTitleText {
            get {
                return ResourceManager.GetString("MyQuestionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in web browser.
        /// </summary>
        internal static string NavigateOKText {
            get {
                return ResourceManager.GetString("NavigateOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sure.
        /// </summary>
        internal static string NotSureButtonText {
            get {
                return ResourceManager.GetString("NotSureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no Upper House.
        /// </summary>
        internal static string NoUpperHousePickerTitle {
            get {
                return ResourceManager.GetString("NoUpperHousePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string OrHeaderText {
            get {
                return ResourceManager.GetString("OrHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other MPs who should answer the question.
        /// </summary>
        internal static string OtherMPAnswerFilterLabelText {
            get {
                return ResourceManager.GetString("OtherMPAnswerFilterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other MPs who should raise the question in Parliament.
        /// </summary>
        internal static string OtherMPRaiseFilterLabelText {
            get {
                return ResourceManager.GetString("OtherMPRaiseFilterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Profile.
        /// </summary>
        internal static string OtherUserProfileTitle {
            get {
                return ResourceManager.GetString("OtherUserProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string PostcodeHeaderText {
            get {
                return ResourceManager.GetString("PostcodeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Public Authority.
        /// </summary>
        internal static string PublicAuthorityButtonText {
            get {
                return ResourceManager.GetString("PublicAuthorityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish New Question!.
        /// </summary>
        internal static string PublishQuestionButtonText {
            get {
                return ResourceManager.GetString("PublishQuestionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Details.
        /// </summary>
        internal static string QuestionDetailsTitle {
            get {
                return ResourceManager.GetString("QuestionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question was edited successfully..
        /// </summary>
        internal static string QuestionEditSuccessfulPopupText {
            get {
                return ResourceManager.GetString("QuestionEditSuccessfulPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question: .
        /// </summary>
        internal static string QuestionHeaderText {
            get {
                return ResourceManager.GetString("QuestionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Writer:.
        /// </summary>
        internal static string QuestionWriterHeaderText {
            get {
                return ResourceManager.GetString("QuestionWriterHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, we&apos;ll help you direct your question to where it might get answered. Choose by whom should it be raised by....
        /// </summary>
        internal static string RaiseQuestionHeaderText {
            get {
                return ResourceManager.GetString("RaiseQuestionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise My Question.
        /// </summary>
        internal static string RaiseQuestionTitle {
            get {
                return ResourceManager.GetString("RaiseQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvote good questions, or click for more detail.
        /// </summary>
        internal static string ReadingPageHeader1 {
            get {
                return ResourceManager.GetString("ReadingPageHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Questions.
        /// </summary>
        internal static string ReadQuestionsTitle {
            get {
                return ResourceManager.GetString("ReadQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Questions.
        /// </summary>
        internal static string RecentQuestionsTitle {
            get {
                return ResourceManager.GetString("RecentQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register MP Account.
        /// </summary>
        internal static string RegisterMPAccountButtonText {
            get {
                return ResourceManager.GetString("RegisterMPAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Organisation Account.
        /// </summary>
        internal static string RegisterOrganisationAccountButtonText {
            get {
                return ResourceManager.GetString("RegisterOrganisationAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Answer.
        /// </summary>
        internal static string SaveAnswerButtonText {
            get {
                return ResourceManager.GetString("SaveAnswerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read questions from {0}.
        /// </summary>
        internal static string SeeQuestionsButtonText {
            get {
                return ResourceManager.GetString("SeeQuestionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectButtonText {
            get {
                return ResourceManager.GetString("SelectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected!.
        /// </summary>
        internal static string SelectedButtonText {
            get {
                return ResourceManager.GetString("SelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a state.
        /// </summary>
        internal static string SelectStateWarningText {
            get {
                return ResourceManager.GetString("SelectStateWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your serverconfig.json file..
        /// </summary>
        internal static string ServerConfigErrorRecommendation {
            get {
                return ResourceManager.GetString("ServerConfigErrorRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration error..
        /// </summary>
        internal static string ServerConfigErrorText {
            get {
                return ResourceManager.GetString("ServerConfigErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Questions.
        /// </summary>
        internal static string SimilarQuestionsTitle {
            get {
                return ResourceManager.GetString("SimilarQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this step.
        /// </summary>
        internal static string SkipStepButton {
            get {
                return ResourceManager.GetString("SkipStepButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Drafting.
        /// </summary>
        internal static string StartDraftingButtonText {
            get {
                return ResourceManager.GetString("StartDraftingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateHeaderText {
            get {
                return ResourceManager.GetString("StateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;ll help you direct your question to where it might get answered.
        /// </summary>
        internal static string Step2BodyText1 {
            get {
                return ResourceManager.GetString("Step2BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should it be raised by....
        /// </summary>
        internal static string Step2BodyText2 {
            get {
                return ResourceManager.GetString("Step2BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Parliamentary Committee, such as Senate Estimates?.
        /// </summary>
        internal static string Step2BodyText3 {
            get {
                return ResourceManager.GetString("Step2BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or by your MP, perhaps in a special session for constituent questions?.
        /// </summary>
        internal static string Step2BodyText4 {
            get {
                return ResourceManager.GetString("Step2BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or by some other MP?.
        /// </summary>
        internal static string Step2BodyText5 {
            get {
                return ResourceManager.GetString("Step2BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a journalist or other RightToAsk participant?.
        /// </summary>
        internal static string Step2BodyText6 {
            get {
                return ResourceManager.GetString("Step2BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or are you just not sure?.
        /// </summary>
        internal static string Step2BodyText7 {
            get {
                return ResourceManager.GetString("Step2BodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street number and name.
        /// </summary>
        internal static string StreetHeaderText {
            get {
                return ResourceManager.GetString("StreetHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details were successfully updated..
        /// </summary>
        internal static string SuccessfullyUpdatedAccountText {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters - Tap to edit.
        /// </summary>
        internal static string TapToEditFiltersText {
            get {
                return ResourceManager.GetString("TapToEditFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be answered by.
        /// </summary>
        internal static string ToBeAnsweredByText {
            get {
                return ResourceManager.GetString("ToBeAnsweredByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Now.
        /// </summary>
        internal static string TrendingNowButtonText {
            get {
                return ResourceManager.GetString("TrendingNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string UIDHeaderText {
            get {
                return ResourceManager.GetString("UIDHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter UserID.
        /// </summary>
        internal static string UIDPlaceholderText {
            get {
                return ResourceManager.GetString("UIDPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        internal static string UpdateAccountButtonText {
            get {
                return ResourceManager.GetString("UpdateAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MPs.
        /// </summary>
        internal static string UpdateMPsButtonText {
            get {
                return ResourceManager.GetString("UpdateMPsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1.
        /// </summary>
        internal static string UpvoteButtonText {
            get {
                return ResourceManager.GetString("UpvoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Upvote.
        /// </summary>
        internal static string UpvotedButtonText {
            get {
                return ResourceManager.GetString("UpvotedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvotes: .
        /// </summary>
        internal static string UpvotesHeaderText {
            get {
                return ResourceManager.GetString("UpvotesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfileTitle {
            get {
                return ResourceManager.GetString("UserProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}&apos;s profile.
        /// </summary>
        internal static string ViewOtherUserProfile {
            get {
                return ResourceManager.GetString("ViewOtherUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open it in a web browser?.
        /// </summary>
        internal static string WebNavigationRequest {
            get {
                return ResourceManager.GetString("WebNavigationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link is outside Right To Ask .
        /// </summary>
        internal static string WebNavigationWarning {
            get {
                return ResourceManager.GetString("WebNavigationWarning", resourceCulture);
            }
        }
    }
}
