name: Build Xamarin.iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
#          If this starts breaking check Xamarin bundles here https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xamarin-bundles
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=15.40

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore ./RightToAskClient/RightToAskClient.sln

      - name: Build
        run: msbuild ./RightToAskClient/RightToAskClient/RightToAskClient.iOS/RightToAskClient.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
